### ISSUE TITLE
DialogFlow in frondend setting (React)

### ISSUE THREAD

**Issue by Luttik** [googleapis/nodejs-dialogflow#21]
- OS: Windows 10 
  - Node.js version: v9.4.0
  - npm version: 5.6.0
  - dialogflow version: 0.1.0

#### Issue
When I try to include the dialogflow SDK into my react app I get the following error.

![image](https://user-images.githubusercontent.com/6634187/35433693-a85eba1e-0284-11e8-82b2-1b1b37ad49a0.png)

As I understand from what I've read this is because fs is a server-side module rather than a client-side module. But this API does seem to be meant as a front-end api. So I hope this issue can be solved.

#### Steps to reproduce

  1. run in console `create-react-app reporduce_issue`
  2. run in console `npm install --save dialogflow`
  3. add `import {SessionsClient} from 'dialogflow'` to App.js

I hope this can be solved.

Thanks!

**Comment by hboylan** [comment]
`fs` is a default NodeJS package. You probably want to use the [JS client](https://github.com/dialogflow/dialogflow-javascript-client) for your project.

Looks like they're still working on porting it to v2...

**Comment by htasha** [comment]
@hboylan yes but these library will not be deprecated? in the docs they said:

> When starting a new project, use Dialogflow's V2 and V2 SDKs listed above.

https://dialogflow.com/docs/sdks

**Comment by hboylan** [comment]
@htasha Correct. V1 is absolutely deprecated.

I just wanted to point out that the reason @Luttik is unable to use this Dialogflow client library is because it's for NodeJS, not client-side JavaScript (React in this case). My recommendation is to plug this library into a lightweight express server for your app.

**Comment by htasha** [comment]
@hboylan That's what I though. As @Luttik I wanted to use it for the same purpose but I find it difficult to understand the available documentation the `samples/` here and the reference there: https://dialogflow.com/docs/reference/api-v2/rest are not as beginner friendly if you wanted to start building your own front end applications. Hope they will improve this, since this it's an amazing tool.

**Comment by JustinBeckwith** [comment]
Greetings!  We're tracking webpack support over in #16.  I'm going to close this one out for now.
