### ISSUE TITLE
Facebook handover

### ISSUE THREAD

**Issue by BenjaminHoegh** [googleapis/nodejs-dialogflow#23]
Does Dialogflow have support for the Facebook handover protocol?

**Comment by kr05** [comment]
Can we get an answer on this please? I'm trying to get my bot to receive standby and messaging_handover events from facebook, to no avail. I've searched on the forums and stack overflow, but there are unanswered questions on those platforms as well.

**Comment by nbsoluren** [comment]
Same problem here. I'm trying to modularize my agent's capabilities but can't seem to get past this issue.

**Comment by aknad** [comment]
Did you found a way to do it? 
thanks

**Comment by baninaveen** [comment]
i need too

**Comment by jarrodeqtr** [comment]
I know this isn't a real answer, because I haven't tried it myself, but I believe at the moment you might need to roll your own requests to and from facebook. I have used this sample to get the handover working, so perhaps if you can mash the 2 together then you might have something working?

https://github.com/fbsamples/messenger-platform-samples/tree/master/handover_protocol

**Comment by callmehiphop** [comment]
You can find a list of integrations at https://cloud.google.com/dialogflow-enterprise/docs/integrations/, however I can't find any mention of the handover protocol specifically.

@nnegrey do you have any insights here?

**Comment by nnegrey** [comment]
I'm not certain, but the link you provided above is probably the best solution.
