### ISSUE TITLE
Agent Updates

### ISSUE THREAD

**Issue by beeme1mr** [googleapis/nodejs-dialogflow#25]
Is it possible to create and update an Agents configuration via the API?  I would like to be able to promote our agent through the a CI pipeline but the webhook configuration would be different per environment.  The current examples show how you can update an agent from a zip but that would make environment specific changes difficult.

Any examples or recommendations would be appreciated.

**Comment by peternann** [comment]
@beeme1mr  - I'm working towards releasing a CLI tool on npm that exercises (for a start) the 'get' and 'update' methods in this API.

But I have similar questions to you. The new API has CRUD (Create, Read/Get, Update, Delete) methods for both Intents and Entities, but I only see a 'getAgent' for the top level stuff like project Timezone, matchMode and classificationThreshold.

Devs: In the new V2 world, is there anything like the export/import/restore functionality, that seems to still follow V1 formats???
Is the intention that we KEEP USING those zip-based methods even now with a V2 agent?

I would guess not since the Intent/Entity file formats seem to have changed non-trivially...

A bit unclear what the road forward here is.
Can anyone clarify?

**Comment by nnegrey** [comment]
I'm not sure if what you're looking for is supported in V2. 
https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2

Is creating an agent over the API something you'll be doing regularly and for multiple GCP projects?
or are you continually recreating the agent for the one project?
