### ISSUE TITLE
Custom event parameters are ignored

### ISSUE THREAD

**Issue by mwoop** [googleapis/nodejs-dialogflow#322]
I am sending a custom welcome event called "demo-welcome" via v2 with version 0.8.2

```javascript
{
	"session":"projects/XXXXXXXXXXXX/agent/sessions/20055814231515",
	"queryInput": {
		"event": {
			"name":"demo-welcome",
			"parameters": {
				"party":"123456"
			},
			"languageCode":"de"
			}
		}
}
```
The event fires correctly but unfortunately parameter party cannot be accessed: #demo-welcome.party does not exist.

Any help is appreciated.
Mark.

**Comment by callmehiphop** [comment]
Hi @mwoop the issue is that `parameters` needs to be formatted as [protobuf Struct](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct). I actually put together a little [utility module](https://github.com/callmehiphop/pb-util) to help with conversions if you're interested

```js
const {struct} = require('pb-util');
const parameters = struct.encode({party: '123456'});
```

**Comment by mwoop** [comment]
Hi @callmehiphop - that solved my issue. Thanks a lot.

**Comment by callmehiphop** [comment]
@mwoop awesome, glad to hear it!
