### ISSUE TITLE
How to create followup intents with batchUpdateIntents?

### ISSUE THREAD

**Issue by thinkty** [googleapis/nodejs-dialogflow#642]
Hello,

I am trying to use this DialogFlow API client to manage the intents of my agent and I have to use [`batchUpdateIntents`](https://googleapis.dev/nodejs/dialogflow/latest/v2.IntentsClient.html#batchUpdateIntents) for my task as I get the whole flowchart at once and parse it into a batch of intents. Almost always, there are several followup intents within the batch of intents. However, I am having trouble trying to create followup intents within the batch.

I saw [this](https://github.com/googleapis/nodejs-dialogflow/issues/479) issue and several [others](https://github.com/googleapis/nodejs-dialogflow/issues/114) but it seems that they are all using [`createIntent`](https://googleapis.dev/nodejs/dialogflow/latest/v2.IntentsClient.html#createIntent). instead of `batchUpdateIntents`.

When I try to create followup intents using `batchUpdateIntents`, I get the following error message:
```
Error: 3 INVALID_ARGUMENT: 'WakeUp-100' is not a valid intent ID. Must be a UUID.
```
I gave the parent intent's name to `rootFollowupIntentName` and also `parentFollowupIntentName`, but it seems that it requires a UUID.

After a bit of searching, I was able to find [this](https://stackoverflow.com/questions/52647517/dialogflow-invalid-argument-error-on-followup-intent-update) Stackoverflow post stating that the intent ID is determined by Dialogflow and it cannot be modified by the user. 

Is there a way to create a followup if the UUID of the intent has not been created yet?
Thank you.

**Comment by thinkty** [comment]
Although I am tempted to use multiple `createIntent` calls and get the uuid from the response, but the [best practices](https://cloud.google.com/dialogflow/docs/best-practices#batch) states that I shouldn't spam those. How many calls do you think is too much for individual calls?

**Comment by thinkty** [comment]
I no longer need to use followup intents, but I will leave this open as someone else might stumble upon this problem.

**Comment by munkhuushmgl** [comment]
I will look into this .

**Comment by munkhuushmgl** [comment]
Best practice would be --> batch intents one layer at a time:
 1. All non follow intents
 2. follow up intents
 3. follow up follow up intents

Another possibility would be to not use followup intents. Instead just configure a root intent AA with output context. "AA-followup" and any followup intents to AA include input context "AA-followup". This would be behave the same in the practice, it just wouldn't enable the followup/dropdown UI in the console. I prefer this method because it reusing/rearchitecting followup intents easier.

With this note, I am closing this issue.

Feel free to reopen this issue.
