### ISSUE TITLE
Timezone response

### ISSUE THREAD

**Issue by JuanUnited** [googleapis/nodejs-dialogflow#791]
Hi there!

I'm looking how to set a response based on my timezone, like "Hi, we are out of hour, come later"

**Comment by sgreenberg** [comment]
Thank you for filing this issue. This Github repo is used for issues with the Node.js Dialogflow client library . This issue appears to be a question about your specific implementation rather than a problem with the product or library. Unfortunately this is not a staffed support channel for Dialogflow. Here are some options you can consider: Google Cloud Platform support options are at https://cloud.google.com/support/. Community support is provided at https://stackoverflow.com/questions/tagged/dialogflow-es.

If you believe that part of this issue still needs to be addressed in this client library, then feel free to re-open this issue with more information.
