### ISSUE TITLE
Ending sessions using the handshake protocol from Messenger

### ISSUE THREAD

**Issue by ceekaymats** [googleapis/nodejs-dialogflow#808]
Hello, I have two Dialogflow agents connected to two Facebook Messenger Pages, one is the primary page and the second is the secondary. I am using the handshake protocol to handle control as to which Dialogflow agent responds to which intent. Is it possible to create a session that expires and automatically returns conversation control back to the primary agent after a specific time frame of inactivity?

An example of the desired result would be :

User : hi 
Agent (primary page): Hi how can I help you?
User : May I speak to a live agent?
* Handshake protocol switches control to the live agent (secondary agent) *
Live Agent (secondary page): Hello from live agent, how can I help?

* User is inactive for a specific amount of time*
* Session Ends and control goes back to primary page. *

User : hey
Agent (primary page): Hi how can I help you?

Thanks in advance :)

**Comment by b-loved-dreamer** [comment]
Hi @ceekaymats — thank you for posting this issue. In my understanding, your problem is divided in two parts: adding a timeout parameter to your session (that starts ticking after it detects that the user stopped interacting with the agent) AND automatically returning control of the conversation back from Secondary Agent to Primary Agent. 

It sounds like you already have the control assigning part ready to go. 

As explained in the ```Dialogflow ES``` documentation: an Agent is the entry point entity that handles interaction with users by translating end-user text or audio during a conversation to structured data that your apps and services can understand. You design and build a Dialogflow agent to handle the types of conversations required for your system. A Dialogflow agent is similar to a human call center agent. You train them both to handle expected conversation scenarios, and your training does not need to be overly explicit.

The next entity under the ```Dialogflow ES``` logical hierarchy is the ```Intent```, which categorizes an end-user's intention for one conversation turn. 

Here your problem scenario describes a control transfer situation at the Agent-To-Agent level using the handshake protocol. I think I'd need to get more context from you to see what you're doing at the coding/technical level. Please share more information and context if you can. At that point we can see if our library has the features to handle your problem.

**Comment by b-loved-dreamer** [comment]
I am now closing this issue as it may no longer be relevant. Feel free to reopen.
