### ISSUE TITLE
Where are Typescript typings, eg QueryResult?

### ISSUE THREAD

**Issue by peternann** [googleapis/nodejs-dialogflow#903]
This package claims to support Typescript typings since 2.0.0, but I cannot find any of the types I expect in the package, nor any example Typescript code that uses the package.

If Typescript is indeed supported, could we get at least one working example in the example set, that is in Typescript?

1) Is this a client library issue or a product issue?
It's a library issue.

2) Did someone already solve this?
Not that I have found
3) Do you have a support contract?
I do. I have raised. But also asking here publicly for the benefit of others.

#### Environment details

  - `@google-cloud/dialogflow` version: 4.5.0

#### Steps to reproduce

  1. Try to reference the Typescript type for dialogflow...QueryResult any Typescript code
  2. Can't find the types like "QueryResult" or "DetectIntentRequest" in the package

**Comment by galz10** [comment]
Hi @peternann we're planning to add expected types soon, i'll create a feature request to add a typescript example. I'll close this issue out due to it not being issue it's a feature request but if anything else comes up pertaining to typescript and this library feel free to reopen or create another issue.
